#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v4
# autospec commit: da8b975
#
Name     : bolt
Version  : 0.9.7
Release  : 15
URL      : https://gitlab.freedesktop.org/bolt/bolt/-/archive/0.9.7/bolt-0.9.7.tar.gz
Source0  : https://gitlab.freedesktop.org/bolt/bolt/-/archive/0.9.7/bolt-0.9.7.tar.gz
Summary  : Thunderbolt device manager
Group    : Development/Tools
License  : LGPL-2.0+ LGPL-2.1
Requires: bolt-bin = %{version}-%{release}
Requires: bolt-config = %{version}-%{release}
Requires: bolt-data = %{version}-%{release}
Requires: bolt-libexec = %{version}-%{release}
Requires: bolt-license = %{version}-%{release}
Requires: bolt-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(polkit-gobject-1)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
bolt is a system daemon to manage Thunderbolt devices via a D-BUS
API. Thunderbolt 3 introduced different security modes that require
devices to be authorized before they can be used. The D-Bus API can be
used to list devices, enroll them (authorize and store them in the
local database) and forget them again (remove previously enrolled
devices). It also emits signals if new devices are connected (or
removed). During enrollment devices can be set to be automatically
authorized as soon as they are connected.  A command line tool, called
boltctl, can be used to control the daemon and perform all the above
mentioned tasks.

%package bin
Summary: bin components for the bolt package.
Group: Binaries
Requires: bolt-data = %{version}-%{release}
Requires: bolt-libexec = %{version}-%{release}
Requires: bolt-config = %{version}-%{release}
Requires: bolt-license = %{version}-%{release}
Requires: bolt-services = %{version}-%{release}

%description bin
bin components for the bolt package.


%package config
Summary: config components for the bolt package.
Group: Default

%description config
config components for the bolt package.


%package data
Summary: data components for the bolt package.
Group: Data

%description data
data components for the bolt package.


%package libexec
Summary: libexec components for the bolt package.
Group: Default
Requires: bolt-config = %{version}-%{release}
Requires: bolt-license = %{version}-%{release}

%description libexec
libexec components for the bolt package.


%package license
Summary: license components for the bolt package.
Group: Default

%description license
license components for the bolt package.


%package services
Summary: services components for the bolt package.
Group: Systemd services
Requires: systemd

%description services
services components for the bolt package.


%prep
%setup -q -n bolt-0.9.7
cd %{_builddir}/bolt-0.9.7
pushd ..
cp -a bolt-0.9.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708372922
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/bolt
cp %{_builddir}/bolt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/bolt/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/boltctl
/usr/bin/boltctl

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/90-bolt.rules

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.freedesktop.bolt.xml
/usr/share/dbus-1/system-services/org.freedesktop.bolt.service
/usr/share/dbus-1/system.d/org.freedesktop.bolt.conf
/usr/share/polkit-1/actions/org.freedesktop.bolt.policy
/usr/share/polkit-1/rules.d/org.freedesktop.bolt.rules

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/boltd
/usr/libexec/boltd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bolt/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/bolt.service
